_welcome:
    pattern:  /
    defaults: { _controller: DevophpEtcdBundle:Welcome:index }

_index:
    resource: "@DevophpEtcdBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /etcdadmin